apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudvr-perfguard-ai
  name: cloudvr-perfguard-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudvr-perfguard-ai
  template:
    metadata:
      labels:
        app: cloudvr-perfguard-ai
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: production
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              key: gemini-api-key
              name: api-keys
        image: cloudvr-perfguard-ai:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        name: cloudvr-perfguard-ai
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
