"""Type definitions for TextWorld agents.

These types were originally in atroposlib.type_definitions but were removed.
Defined locally here to avoid conflicts with main library updates.
"""

from typing import List, Optional
from typing_extensions import TypedDict

from atroposlib.type_definitions import Message


class AtroposAgentAction(TypedDict):
    """Represents a single action generated by the agent."""
    action_text: str
    api_error: bool
    score: float


class AtroposAgentTurn(TypedDict):
    """Represents a single turn in the game log."""
    turn_number: int
    observation_message: Message
    alternatives: List[AtroposAgentAction]
    selected_alternative: Optional[int]


class AtroposAgentActionLog(TypedDict):
    """Complete game log containing all turns."""
    turn: List[AtroposAgentTurn]