import logging
import math
from typing import Optional, Dict, Any, List
from .metrics import WorkloadMetrics

logger = logging.getLogger(__name__)

class ScalingController:
    """
    Decides the "Desired Actor Count" based on workload metrics.
    Uses a dampened calculation with hysteresis to avoid flapping.
    """
    def __init__(
        self,
        min_actors: int = 1,
        max_actors: int = 20,
        target_pressure: float = 1.0,
        scaling_threshold: float = 0.2, # ±20%
        cooldown_seconds: int = 60,
        max_step_change: int = 4
    ):
        self.min_actors = min_actors
        self.max_actors = max_actors
        self.target_pressure = target_pressure
        self.scaling_threshold = scaling_threshold
        self.cooldown_seconds = cooldown_seconds
        self.max_step_change = max_step_change
        
        self.last_action_timestamp = 0
        self.current_desired = min_actors

    def calculate_desired(self, metrics: WorkloadMetrics, current_actors: int, pending_actors: int = 0, draining_actors: int = 0) -> int:
        """
        Decides the next target for the number of environment actors.
        - current_actors: Connected and ready
        - pending_actors: Process started but not registered
        - draining_actors: Process signaled to exit but still finishing work
        """
        now = metrics.timestamp
        pressure = metrics.rollout_pressure
        # Effective capacity = Connected + Pending
        effective_actors = current_actors + pending_actors
        
        # 1. Sync internal state
        if abs(self.current_desired - current_actors) > 0:
             logger.debug(f"Controller: Syncing internal state {self.current_desired} -> {current_actors}")
             self.current_desired = current_actors

        # 2. Check cooldown
        if now - self.last_action_timestamp < self.cooldown_seconds:
            remaining = int(self.cooldown_seconds - (now - self.last_action_timestamp))
            logger.debug(f"Controller: In cooldown ({remaining}s remaining). Holding at {self.current_desired} actors.")
            return self.current_desired

        # 3. Sensitivity check (Hysteresis)
        if abs(pressure - self.target_pressure) < self.scaling_threshold:
            logger.debug(f"Controller: Pressure {pressure:.2f} within threshold. No action.")
            return self.current_desired

        # 4. Calculate target
        # We use current_actors as the base for normalization because the 'pressure' 
        # metric is generated by the work of currently connected actors.
        base_count = max(current_actors, 1)
        raw_target = math.ceil(base_count * (pressure / self.target_pressure))
        
        # 5. Latency/Drain Compensation
        if raw_target > current_actors:
            # Scale UP: Don't launch more if pending capacity already reaches the target
            if effective_actors >= raw_target:
                logger.debug(f"Controller: Target {raw_target} satisfied by effective capacity ({effective_actors}).")
                return current_actors
        elif raw_target < current_actors:
            # Scale DOWN: Don't kill more if we are already draining enough
            if (current_actors - draining_actors) <= raw_target:
                logger.debug(f"Controller: Target {raw_target} satisfy during ongoing drainage ({draining_actors}).")
                return current_actors
        
        # 6. Apply step constraints
        diff = raw_target - current_actors
        if abs(diff) > self.max_step_change:
            logger.info(f"Controller: Step change {diff} exceeds max_step_change. Capping.")
            raw_target = current_actors + (self.max_step_change if diff > 0 else -self.max_step_change)

        # 7. Apply bounds
        final_target = max(self.min_actors, min(self.max_actors, raw_target))
        
        if final_target != current_actors:
            self.last_action_timestamp = now
            self.current_desired = final_target
            direction = "UP" if final_target > current_actors else "DOWN"
            logger.info(f"Controller DECISION: Scale {direction} {current_actors} -> {final_target} "
                        f"(Pressure: {pressure:.2f}, Pending: {pending_actors}, Draining: {draining_actors})")
        
        return final_target
