"""
Type definitions for AtroposAgent.
"""

from typing import List, Optional, TypedDict
from atroposlib.type_definitions import Message


class AtroposAgentAction(TypedDict):
    """Represents an action generated by the agent."""
    action_text: str
    api_error: bool
    score: float


class AtroposAgentTurn(TypedDict):
    """Represents a turn in the agent's game log."""
    turn_number: int
    observation_message: Message
    alternatives: List[AtroposAgentAction]
    selected_alternative: Optional[int]


class AtroposAgentActionLog(TypedDict):
    """Complete action log for an agent."""
    turn: List[AtroposAgentTurn]