# Environment configuration
env:
  group_size: 16
  tokenizer_name: "gpt2"
  use_wandb: true
  rollout_server_url: "http://localhost:8000"
  wandb_name: "refusal_benchmark"
  total_steps: 500
  batch_size: 512
  max_token_length: 1024
  data_file: "test_set.jsonl"
  max_eval_samples: 4000
  classifier_type: "openai"
  eval_temperature: 0.7
  train_temperature: 0.8
  eval_max_tokens: 1024
  train_max_tokens: 1024
  use_label_0_for_training: true
  data_dir_to_save_evals: "results/refusal_evaluation"

# Server configurations - [0] main model, [1] classifier
openai:
  - model_name: "gpt-4o-mini"
    base_url: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"
    num_max_requests_at_once: 8
    num_requests_for_eval: 32
    server_type: "openai"
    timeout: 120
    weight: 1.0

  - model_name: "minos-v1"
    base_url: "http://localhost:1234/v1"
    api_key: "${MINOS_API_KEY}"
    num_max_requests_at_once: 8
    num_requests_for_eval: 32
    server_type: "openai"
    timeout: 120
    weight: 1.0

slurm: false
testing: false
